from util.terminaloutput.colors import RED_COLOR, BLUE_COLOR, YELLOW_COLOR, NO_COLOR

ERROR_SYMBOL = f"{RED_COLOR}<!>{NO_COLOR}"
WARN_SYMBOL = f"{YELLOW_COLOR}<!>{NO_COLOR}"
INFO_SYMBOL = f"{BLUE_COLOR}<!>{NO_COLOR}"
