import pygame

EMPTY_BORDER = 20
WIDTH, HEIGHT = 400 + EMPTY_BORDER*2, 500 + EMPTY_BORDER
ROWS, COLS = 3, 3
SQUARE_SIZE = (WIDTH - EMPTY_BORDER*2) //COLS

# RGB
WHITE = (255, 255, 255)
BLACK = (0, 0, 0) 

# Board Pieces
X_PIECE = 'X'
O_PIECE = "O"
EMPTY = ' '